#!/usr/bin/env bash

cd "${BASH_SOURCE%/*}"
source maven.bash

[[ ! -z $1 ]] && releaseVersion="$1" || { echo "You must specify a release version!"; exit; }

version="${1}"

if [[ ${version} == *-e ]]
then
  releaseType="sts"
else
  releaseType="lts"
fi

prestoRangerVersion=2.0.35
tableOperatorVersion=336-e.0
prestoVersion=$(echo ${version} | sed -e 's/\..*$//' -e 's/-e//')
enterpriseVersion=$(echo ${version} | sed -e 's/\..*$//' -e 's/-//')

echo "             version: ${version}"
echo "        releaseType:  ${releaseType}"
echo "       prestoVersion: ${prestoVersion}"
echo "   enterpriseVersion: ${enterpriseVersion}"
echo "tableOperatorVersion: ${tableOperatorVersion}"
echo " prestoRangerVersion: ${prestoRangerVersion}"
