#!/usr/bin/env bash

cd "${BASH_SOURCE%/*}"
source maven.bash

[ ! -z "$1" ] && releaseVersion="$1" || { echo "You must specify a release version!"; exit; }

mavenCoordinateToArtifactPath "ca.vanzyl.mrel:mrel:1.0"
echo "MAVEN_PROJECT_VERSION from  arg0 = ${1}"
echo "MAVEN_PROJECT_VERSION from envar = ${MAVEN_PROJECT_VERSION}"
